# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Eoyc < Formula
  desc "Encoding only your choices"
  homepage "https://github.com/hahwul/eoyc"
  url "https://github.com/hahwul/eoyc/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "a4506838acb77882e5b6d32cca0530c38742037c343a1013778c25454adb8d70"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
system "shards build --release --no-debug --production"
bin.install "bin/eoyc"
  end

  test do
    system "{bin}/eoyc", "-v"
  end
end
